# Generated by Django 4.1.7 on 2023-03-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_user_is_user_user_is_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('All States', 'All States'), ('AL', 'AL'), ('AK', 'AK'), ('AZ', 'AZ'), ('AR', 'AR'), ('CA', 'CA'), ('CO', 'CO'), ('CT', 'CT'), ('DE', 'DE'), ('DC', 'DC'), ('FL', 'FL'), ('GA', 'GA'), ('HI', 'HI'), ('ID', 'ID'), ('IL', 'IL'), ('IN', 'IN'), ('IA', 'IA'), ('KS', 'KS'), ('KY', 'KY'), ('LA', 'LA'), ('ME', 'ME'), ('MD', 'MD'), ('MA', 'MA'), ('MI', 'MI'), ('MN', 'MN'), ('MS', 'MS'), ('MO', 'MO'), ('MT', 'MT'), ('NE', 'NE'), ('NV', 'NV'), ('NH', 'NH'), ('NJ', 'NJ'), ('NM', 'NM')], max_length=10)),
                ('document', models.CharField(choices=[('All Documents', 'All Documents'), ('QCD', 'QCD'), ('SWD', 'SWD'), ('GWD', 'GWD'), ('DIL', 'DIL')], max_length=20)),
                ('client', models.CharField(choices=[('All Clients', 'All Clients'), ('TF', 'TF'), ('WFG', 'WFG'), ('SLINK', 'SLINK'), ('AMR', 'AMR')], max_length=20)),
                ('information', models.CharField(max_length=100)),
            ],
        ),
    ]
